### ISSUE TITLE
Reducing the size of the float button

### ISSUE THREAD

**Issue by hongquang198** [niltondiniz/float_button_overlay#1]
Hi. I'd like to reduce the size of the floating icon after app exiting since the icon has a white transparent border around it. How would I disable that? Thanks

**Comment by hongquang198** [comment]
Found it! To change the wrap around the floating icon, navigate to External Libraries/Flutter Plugin/float_button_overlay/android/src/man/res/layout_round_shape.xml
and change the width/height there.

**Comment by niltondiniz** [comment]
Hi!
I'll create a property to make it visible/invisible, and other to sets the size values.
