### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by hongquang198** [niltondiniz/float_button_overlay#3]
Hi! I'd like to report an issue when opening and closing the float button overlay.
Due to the nature of the app I'm working on it needs the button to reopen and close quite often (it's a fast lookup function of a dictionary if you're curious)
However the memory doesn't quite discard when I hit the 'Close Button' as in the original example.
Therefore the memory keeps building up whenever I need to reopen the float button.

![Screenshot 2021-05-12 184333](https://user-images.githubusercontent.com/49474671/117969769-0e16d680-b352-11eb-869a-4519103d5474.png)

Overall, this is a really great plugin. And it works great. I'm really glad this exists

**Comment by niltondiniz** [comment]
Hi @hongquang198!
Thanks for use, it's cool your feedback. 
I'll see this now

**Comment by niltondiniz** [comment]
Hi!
Good news, i already identify where memory is leaking. But i'll stress more tests before release it.

**Comment by niltondiniz** [comment]
Done!

**Comment by hongquang198** [comment]
Awesome! It's working great now
